# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  name: 'GP-builders'
  demands:
  - Agent.OS -equals Windows_NT

steps:
  - task: npmAuthenticate@0
    displayName: 'npm Authenticate .npmrc'
    inputs:
      workingFile: .npmrc

  - task: NodeTool@0
    inputs:
      versionSpec: '20.19.4'
    displayName: 'Install Node.js'

  - script: call npm install --legacy-peer-deps
    displayName: 'NPM install'

  - script: call npm run build:main
    displayName: Build

  - task: Npm@1
    displayName: 'npm publish'
    inputs:
      command: publish
      workingDir: dist/ngx-translate-router
      verbose: false
      publishRegistry: useFeed
      publishFeed: '1a840383-65db-4798-8a29-29969affbcd2/d140b87a-6b17-4f2d-839c-9a865a7d5f8d'
